sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t haithanh86/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haithanh86/docker-react npm run test -- --coverage